### ISSUE TITLE
Wrong table name

### ISSUE THREAD

**Issue by InfluxOW** [tizis/laravel-comments#5]
In migration for creating comments votes method's up table name should be comment**S**_votes, not comment_votes

**Comment by iooe** [comment]
Hi, I'm not a native speaker. I saw a lot of discussion about naming tables when creating a Has Many Through relationship. And I did not find the final decision. Most likely, I first used comments_votes, and then changed to comment_votes.

**Comment by InfluxOW** [comment]
Друг, я имею в виду, что у тебя в down методе одно название таблицы, а в up методе - другое)
Из-за этого, если откатываешь миграции, вылезает ошибка

**Comment by iooe** [comment]
Да, я это заприметил после ишью и отправил коммит с фиксом. Спасибо.
