### ISSUE TITLE
Русский пакет с русскими хитростями?

### ISSUE THREAD

**Issue by maiskiykot** [tizis/laravel-comments#6]
Или я тупой или лыжи не едут. В целом пакет отличный, но для начинающих ларавельщиков беда какая-то - не могу разобраться: где формируется выдача комментариев, сортировка. Нет возможности отключить форму ввода, если человек ответил. Я пытался править функции, но ничего даже не меняется. Такие вроде стандартные вещи как _construct просто не реагируют на любые правки. Функции index просто нет. Где собираются комментарии? Подскажите или направьте в нужную сторону.

**Comment by maiskiykot** [comment]
Я писал про CommentController

**Comment by iooe** [comment]
### Выдача:

Запрос — валидация HTTP запроса в реквесте — разбор запроса в контроллере — формирование sql запроса через скоупы модели и методы билдера eloquent в ответе контроллера (на самом деле я бы это сейчас сделал по другому). 

Сортировка — get метод контроллера, `->orderBy($orderBy['column'], $orderBy['direction'])`

### Про форму ввода
Это расширенная функциональность, подразумевается что вы сами можете это быстро реализовать используя библиотеку как основу. 
Можете создать свой класс контроллера, унаследовавшись от встроенного — тогда сможете вносить любые изменения — также нужно будет перезаписать необходимые пути в роутере на свои. 
Также можете сделать форк библиотеки, и после вносить все нужные изменения прямо в исходный код  
Отсутсвие реакции на изменения конструктора — значит вы как то странно вносили изменения.

**Comment by maiskiykot** [comment]
Я и get пробовал менять и другие функции - почти все просто  не реагируют на изменения. Даже просто ставишь // и ноль эмоций. Хотел поменять местами комментарии и форму комментариев - негде сделать. Может больше комментариев в коде спасут положение? И еще раз повторяю вопрос: где и как формируется список комментариев? Как в эту процедуру влезть с правками?

**Comment by tizis** [comment]
`Даже просто ставишь // и ноль эмоций.`

**Comment by iooe** [comment]
`Даже просто ставишь // и ноль эмоций.`

Тогда проблема в вашем уровне понимания работы композера/фреймворка/умении читать и анализировать код. 

Ведь если явно изменить возвращаемое значение функции, но она продолжает возвращать исходные значения — дело явно не в функции? Вы не понятно что и где изменяете, в после говорите что не видно результатов — я вас в первом комментарии явно указал как вы можете модифицировать код. 

Про форму комментариев и комментарии — это во вьюшке. В документации указан момент про шаблон по умолчанию и созданию локальной копии для внесения изменений — скорее всего, вы создали локальную копию вьюшки (/views/vendor/...) и пытаетесь изменять исходные файлы (vendor/tizis/...). 

На все заданные вами вопросы есть ответы в документации. Но ответы не явные — подразумевается что уровень того, кто собирается вносить изменения в работу библиотеки должен быть выше начинающего.

**Comment by maiskiykot** [comment]
К примеру: в большинстве пакетов в шаблон передается массив $comments. У вас прилетает $comment. Почему? В каком месте у вас $comments превращается в $comment? Зачем form вынесена в отдельный шаблон? В таком виде не могу передать переменные для того чтобы убрать форму, если человек уже ответил

**Comment by iooe** [comment]
Окей, приношу извинения за неверные указания в самом начале. 

Я забыл что библиотека поставляется с шаблоном для рендера на сервере.

**Comment by maiskiykot** [comment]
У меня в PHP стаж 16 лет, но ваш пакет ставит меня в тупик. Я не говорю, что он плохой - наоборот, я ему даже звезду поставил, но абсолютно непонятный. Еще раз говорю - я просто по функциям иду и ставлю в функции // вместо кода - все радостно продолжает выводиться. Может список комментов у вас формируется в laravel, но тогда как туда лезть с правками? Вот чего я понять никак не могу

**Comment by iooe** [comment]
Я забыл что библиотека поставляется с шаблоном для рендера на сервер — контроллер нужен только для апи, и это указано в документации.

В ServiceProvider происходит регистрация компонента вьюшки.

 /laravel-comments/resources/views/bootstrap4/components/comments.blade.php 

Основной компонент  — <x-comments :model="$post"/> 

В нем и происходит рендер и все такое.

**Comment by iooe** [comment]
Не рекомендую использовать сервер сайд рендер, и об этом сказано в документации — собственно, поэтому я и забыл что тут есть не только апи.

**Comment by iooe** [comment]
https://github.com/tizis/laravel-comments/blob/master/readme-ru.md#1-рендеринг-на-стороне-сервера

**Comment by iooe** [comment]
Если нужен рендер на стороне сервера и внесение изменений в него — https://github.com/tizis/laravel-comments/blob/master/readme-ru.md#публикация-примера-по-умолчанию-кастомизация-внешнего-вида

**Comment by maiskiykot** [comment]
Речь не о рендере а о процедуре, где собирается $comments - именно туда хочу влезть с правками. Кастомизация самого вывода тоже представляется проблемой, потому что мульон классов и каждый непонятно для чего. Посмотрел laravelista - там раза в три меньше классов, хотя тоже непонятно где $comments формируются. Нужна ясность, чтобы логика размещалась в CommentController и пакет отзывался на любые изменения в функциях, а то здесь как-будто некий большой брат управляет приложением.

**Comment by iooe** [comment]
Это библиотека когда-то отпочковалась от laravelista — мне не понравилась структура его реализации; были чудовищные проблемы с производительностью — по моим пул реквестам последнее было исправлено. 

По количеству классов — их немного. 

Папка Contracts — интерфейсы.
Events — Объекты для событий изменений модели комментариев.  (https://laravel.com/docs/7.x/validation#form-request-validation)
Entity — модели.
Http\Controllers — Два контроллера для АПИ.
Http\Requests — валидация запрсоов к апи  (https://laravel.com/docs/7.x/validation#form-request-validation)
Http\Resources — ресурсы (аналог view, но только для апи) (https://laravel.com/docs/7.x/eloquent-resources)
Policies — настройка прав доступа.
Providers — системные провайдеры, тут происходит регистрация и настройка библиотеки. 
Traits — в ларвел любят использовать тресты (https://habr.com/ru/post/494658/), это удобно.
UseCases — бизнес логика приложения.

У laravelista все тоже самое, но с меньшей функциональностью, большими божественными классами (https://ru.wikipedia.org/wiki/Божественный_объект) и без какой либо иерархии (все в одной папке).


=============


`потому что мульон классов и каждый непонятно для чего.` 
Добро пожаловать в современность — моя структура не идеальна, но она хоть как то соответствует разделению зоны ответсвенности кода и соответствию код стайлам фреймворка. Это намного лучше, чем если бы за все отвечало два огромных класса с содержанием всей логики, и без какого либо разделения на абстракцию. 



` хотя тоже непонятно где $comments формируются.` — повторюсь, это происходит в вьюшке.

`$comments = $model->commentsWithChildrenAndCommenter()->parentless()->get();`


Собственно, также и у указанного вами пакета.

`https://github.com/laravelista/comments/blob/master/resources/views/components/comments.blade.php`

Возможно, сейчас это можно было бы  сделать чуть иначе — с еще большим разделением кода и магией — но я знаю только такой способ работы с переменными при использовании blade компонентов в ларавел

=====

`У меня в PHP стаж 16 лет, но ваш пакет ставит меня в тупик. `

Вам нужно актуализировать свои знания по языку и современной архитектуре в ПХП. Это не упрек, но язык и используемые паттерны проектирования сильно изменились за эти годы — документация ларавел ответила бы на почти все  задаваемые вами выше вопросы по поводу устройства этой библиотеки. 

PS Пул реквест в laravelista

https://github.com/laravelista/comments/pull/25#issuecomment-442898604

**Comment by maiskiykot** [comment]
Почему в HTTP контроллеры для апи? Разве это не в requests должно лежать? Сам контроллер CommentController и должен рулить для http. Вы попробуйте заглушить процедуры в этом классе - почти все - и комменты будут работать. Это неправильно, особенно в show и _construct или index. Я не так давно занимаюсь ларавел, но почти все скачанные пакеты сам правил и там четкая организация - все собрано в основной контроллер а остальные классы вспомогательные. В вашем пакете просто какой-то ахтунг - никакой логики не прослеживается и комментарии хромают. Почему у вас комменты во вьюшке собираются? Это вы считаете правильным?

**Comment by iooe** [comment]
requests — это валидация запроса 
https://laravel.com/docs/7.x/validation#form-request-validation

Вы игнорируете мои объяснения и ссылки на документацию. 

`CommentController и должен рулить для http` — он это и делает. Он работает с АПИ. 

`Это неправильно, особенно в show и _construct или index. `— вы мысли в рамках контроллера как посредника для вьюшки и божественного объекта. Вы не понимаете как работают трейты и модели — я уже сказал что это контроллер апи. Единственная проблема — это то, что контроллер не лежит в под директории Аpi, но логика здесь простая — Blade компонент НЕ МОЖЕТ работать напрямую с контроллером (правка —можно разделить логику и представление начиная с 7 версии, но это ломает обратную совместимость, да и с контроллерами никак это не связано). 


`Почему у вас комменты во вьюшке собираются? Это вы считаете правильным?`

Это я считаю неправильным. И это мне не нравится. Но, в ларавел 5 нельзя было иначе — только с обновлением вью компонентов в 7 версии появилась возможность разделения логики и рендера в компонентах (https://laravel.com/docs/7.x/blade#passing-data-to-components) но это полностью сломает обратную связь между 5-6-7 версией и сделает кастомизацию менее удобной. 
Комментарии не собираются во вьюшке — вся логика вынесена в трейты и не анемичные модели, во вьюшке происходит только получение данных через скопы и связи — это неприятно, но в рамках допустимого. 

Мне надоело отвечать на странные вопросы, ответы на которые можно получить прочитав либо документацию фреймворка, либо документацию библиотеки на русском, или английском языке.

Те пакеты, которые вы использовали — скорее всего — связаны с либо с чистой логикой без представления (роли пользователей, фильтрация данных и так далее), либо с полным жизненным циклом (библиотека-админка с полноценными контролерами представлением и ресурсами, с полноценным рендером через вьюшки и так далее).

Особенно странно слышать критику структуры библиотеки — она, почти полностью, копирует то, что предлагает ларавел в углубленной документации.

**Comment by maiskiykot** [comment]
Я, конечно, не спец в ларавели, но, мне кажется, что сборка комментов должна быть все-таки вынесена в отдельную процедуру - в классе ли, в трейте - нет разницы. Чтобы можно было вносить правки. К примеру, я решил сделать зебру в комментах. Где брать порядковый номер коммента включая дочерние комментарии? Далее - хочу проверять принадлежит ли последний комментарий  текующему юзеру, чтобы прихлопнуть форму, а конец цикла где-то вне шаблона. Как мне зафиксировать последнего ответившего? Вопросов к такой форме дофига и больше. Если тупо копи-паст, то пакет очень неплох, только перенесите форму под комментарии - она ни к селу ни к городу сверху

**Comment by maiskiykot** [comment]
А еще пагинация и куча обычных и привычных мелочей

**Comment by iooe** [comment]
... все это изменяемся и модифицируется в blade файлах, которые специально для модификации можно скопировать локально через команду из инструкции по установке. 

Даже пагинацию можно сделать вмешиваясь только в blade файлы — изменить в строке получения комментариев get() на paginate(N комментариев) и вывести через штатные средства фреймворка навигацию по страницам.

**Comment by maiskiykot** [comment]
$comments = $model->commentsWithChildrenAndCommenter()->parentless()->orderBy('id','desc')->paginate(5);
Ноль эмоций

**Comment by iooe** [comment]
<img width="1833" alt="image" src="https://user-images.githubusercontent.com/16865573/89709301-6e7e7f00-d9a0-11ea-8eb1-a23d13515b48.png">
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/16865573/89709310-80602200-d9a0-11ea-8708-7044853b444c.png">

**Comment by maiskiykot** [comment]
У меня не работает. И у вас paginate(3) а на скрине 4 коммента. Я говорю: вопросов гораздо больше чем ответов

**Comment by maiskiykot** [comment]
Точнее работает. но страницы не выводятся

**Comment by maiskiykot** [comment]
Добавил {{ $comments->links() }}

**Comment by maiskiykot** [comment]
Если добавляешь сортировку - не работает вывод ссылок на страницы. 
    $comments = $model->commentsWithChildrenAndCommenter()->parentless()->paginate(2)->sortByDesc('id');

**Comment by iooe** [comment]
> У меня не работает. И у вас paginate(3) а на скрине 4 коммента. Я говорю: вопросов гораздо больше чем ответов

Четвёртый это дочерний комментарий. Если не нужны дочерние комментарии — валидируйте их в шаблоне.

**Comment by iooe** [comment]
> Если добавляешь сортировку - не работает вывод ссылок на страницы.
> $comments = $model->commentsWithChildrenAndCommenter()->parentless()->paginate(2)->sortByDesc('id');

Неправильная последовательность вызовов методов eloquent.

**Comment by maiskiykot** [comment]
Она никак не работает - или сортировка или пагинация. Я же говорю, что такая сборка приложения не самая верная. По идее нужно на входе сортировать из модели вывод, но ни контроллер ни трейт не реагирует на сортировку.

**Comment by maiskiykot** [comment]
По поводу дочерних комментов - на странице без разницы - дочерние, недочерние - должно все считать - места-то одинаково занимают, что дочерние, что недочерние.

**Comment by iooe** [comment]
<img width="1804" alt="image" src="https://user-images.githubusercontent.com/16865573/89713541-32581800-d9ba-11ea-887d-ac1468f08076.png">
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/16865573/89713553-3edc7080-d9ba-11ea-9ea3-959161997557.png">

**Comment by iooe** [comment]
> По поводу дочерних комментов - на странице без разницы - дочерние, недочерние - должно все считать - места-то одинаково занимают, что дочерние, что недочерние.

Вы говорите очень странные вещи. Вы можете отключить рендер дочерних комментариев — тогда они не будут занимать места.

**Comment by iooe** [comment]
Мне надоело предоставлять консультацию по базовым вещам (вроде порядка вызова методов Eloquent или принципов работы валидация http запросов в ларавел) — можете продолжить дальше задавать вопросы на сайтах вроде qna.habr.com или stackoverflow.com — благо, почти все ваши вопросы основаны на самих компонентах ларавел, а не на особенностях реализации в данной библиотеке..
