### ISSUE TITLE
Comment order desc

### ISSUE THREAD

**Issue by Ziegurd** [tizis/laravel-comments#7]
Hi, Tizis. How to make the comments in descending order base on created_at column?

I tried this in commentsController.php but it didn't work.
`return [
            'success' => true,
            'comments' => CommentResource::collection(
                $model->commentsWithChildrenAndCommenter()
                    ->parentless()
                    ->orderBy(['order_by' => 'created_at', 'order_direction' => 'desc'])
                    ->get()
            ),
            'count' => $model->commentsWithChildrenAndCommenter()->count()
        ];`

**Comment by iooe** [comment]
Hi, replace "orderby" by orderBy('created_at', 'desc')

**Comment by Ziegurd** [comment]
Thanks for the reply. I'll try it later.
